### ISSUE TITLE
Support for Input Types

### ISSUE THREAD

**Issue by timvandam** [ts-safeql/safeql#221] opened 2024-05-16 14:38 UTC
**Is your feature request related to a problem? Please describe.**

I've been reading through the docs, and while it seems like output types are generated, this is not the case for input types. It would be cool to automatically support this. Judging by https://safeql.dev/libraries/sql-tag/usage.html#createtypedsqltag it looks like it's possible to specify input types, but they are not automatically determined to the query. 

**Describe the solution you'd like**

I am not 100% on the typing of template tags, but assuming that it is not possible to have a different type per substitution it would be cool for the `sql` tag to generate an object with a `run` function that accepts a database client and an object with parameters. 

Thanks for considering

**Comment by Newbie012** [comment] 2024-05-16 15:24
Could you provide an example of what you mean by "Input Types"?

SafeQL doesn't ship any runtime code. There is `@ts-safeql/sql-tag`, but it's not directly associated with the plugin.

I built `@ts-safeql/sql-tag` to assist developers in writing safer and more readable queries in legacy ORMs, as I have [explained here](https://safeql.dev/libraries/sql-tag/usage.html#why).

**Comment by karlhorky** [comment] 2024-05-16 15:46
> You would write this:
> 
> ```ts
> const query = sql<{ username: string }, [number]>`SELECT user_id FROM users WHERE user_id = $1`
> ```

How would a user pass in the `userId` at that point? Would `query` return a function that would accept `userId` as a parameter? Eg:

```ts
const results = await query(userId);
```

**Comment by timvandam** [comment] 2024-05-16 15:54
> > You would write this:
> > ```ts
> > const query = sql<{ username: string }, [number]>`SELECT user_id FROM users WHERE user_id = $1`
> > ```
> 
> How would a user pass in the `userId` at that point? Would `query` return a function that would accept `userId` as a parameter? Eg. do you mean something like this?
> 
> ```ts
> const results = await query(userId);
> ```

Having looked more carefully at how safeql works, I think the easiest solution would be to support it as a variable in the `transforms` of `safeql.configs.connections.targets[index]`. This way you could add input types to functions that accept it. E.g. currently there is `{{type}}`, but having `{{inputType}}` would allow supporting some function like
```ts
async function buildTypedQuery<Input, Output>(query: string): { run: (client: DatabaseClient, inputs: Input) => Promise<Output> } {
 // implementation
}

**Comment by karlhorky** [comment] 2024-05-16 16:10
Hmm... trying to follow here... is the following code an accurate full usage example?

```ts
const query = buildTypedQuery<[number], { user_id: number }>(
  'SELECT user_id FROM users WHERE user_id = $1'
);

const results = await query.run(dbClient, [userId]);
```

Also: do you mean that this `buildTypedQuery` is user-defined function?

**Comment by timvandam** [comment] 2024-05-16 16:17
> Hmm... trying to follow here... is the following code an accurate full usage example?
> 
> ```ts
> const query = buildTypedQuery<[number], { user_id: number }>(
>   'SELECT user_id FROM users WHERE user_id = $1'
> );
> 
> const results = await query.run(dbClient, [userId]);
> ```
> 
> Also: do you mean that this `buildTypedQuery` is user-defined function?
> 
> First thoughts: this seems pretty far away from where SafeQL is now... 🤔

Yes, exactly (except with the two type parameters the other way around). I don't know of any library that accepts input types as a parameter, which is why it would be something user defined. I am not sure of SafeQL's internals so its hard for me to judge how far away this is on a technical level. If its all running on a custom type inference engine I can imagine that it can be difficult to implement this. On a feature level it seems to be quite close though

**Comment by karlhorky** [comment] 2024-05-16 16:30
Also, IIUC another detail is that it seems like this would not be connected to your database schema, since you'd have to define the "input types" of what `userId` should be manually.

Maybe you're just looking for TypeScript functions? In the `buildTypedQuery()` example above, I can't see a location that SafeQL would check the type against the PostgreSQL schema - it seems to be that you're trying to check the type of `userId` against `number`.

Maybe a simpler version would be:

```ts
async function queryUser(userId: number) {}
```

You could also pass in a client to that, if that's a useful feature for you.

You could also combine this with SafeQL, so that the returned type is checked against the PostgreSQL schema:

```ts
async function queryUser(userId: number) {
  return await sql<{ user_id: number }>`
    SELECT user_id FROM users WHERE user_id = ${userId}
  `;
}
```

**Comment by timvandam** [comment] 2024-05-16 16:32
It is connected to the database, as the possible types of $1 in `user_id = $1` depend on the `user_id` column

**Comment by karlhorky** [comment] 2024-05-16 16:36
None of the above options are runtime checks - they are all typecheck- and linting-time checks (could also be called "compile-time").

**Comment by timvandam** [comment] 2024-05-16 16:43
Oh wow, I didn't realize it did that. Sorry about the confusion! Guess this issue can be closed then

**Comment by karlhorky** [comment] 2024-05-16 16:51
Nice ok then I'll close it! Feel free to write further in the thread or open new issues if you have any problems!

**Closed by karlhorky** 2024-05-16 16:51 UTC

**Comment by timvandam** [comment] 2024-05-22 17:28
@karlhorky I've started playing around with safeql, and its been great so far but I have one minor point. It seems like currently it is not possible to only allow strictly identical input types, i.e. I am allowed to provide a typescript value array to a varchar, which postgres will simply convert to a string:

```sql
insert into test_table (id, name) values (1, ${[1, 2, 3]});
-- id: integer
-- name: varchar(255)
```

Is it possible to add a strict option that only allows types as they are mapped inside https://github.com/ts-safeql/safeql/blob/main/packages/eslint-plugin/src/utils/ts-pg.utils.ts#L61-L98?

**Comment by karlhorky** [comment] 2024-05-23 06:21
I'm not sure why some values are not typechecked like that (in your example, why the array is not checked against a "string" needed for varchar)

@Newbie012 any insights here? Should this be opened as a feature request?

**Comment by Newbie012** [comment] 2024-05-23 07:20
It appears to be that this mechanism is by design (of PostgreSQL). Should SafeQL disallow patterns that should work in runtime? debatable.

This is considered valid in PostgreSQL:

```sql
CREATE TABLE tbl (name TEXT);
INSERT INTO tbl (name) VALUES (array[1,2,3,4]);
```

you can read more about it [here](https://dba.stackexchange.com/a/194976). TIL.

**Comment by karlhorky** [comment] 2024-05-23 08:08
> Should SafeQL disallow patterns that should work in runtime? debatable.

Yeah, that's a good question, indeed. If something like this were to be added, then maybe it would be best as an option, as @timvandam mentioned.

**Comment by timvandam** [comment] 2024-05-23 11:27
> Should SafeQL disallow patterns that should work in runtime? debatable.

My argument for having such an option would be that TypeScript essentially does this over JavaScript.

To tack on another possible new feature, I noticed that operations involving arrays can fail when using empty arrays due to postgres not being able to infer the type. I think it would be great to have a lint rule that enforces that you add the correct cast for arrays.
As an example:
```ts
const users = [
    { id: 231, name: 'John Doe' },
    { id: 232, name: 'Jane Doe' },
];

await sql`
    INSERT INTO test_table (id, name)
    SELECT id, name
    FROM UNNEST(${users.map((user) => user.id)}, ${users.map((user) => user.name)}) as input(id, name);
`;
-- this works just fine

const users = [];

await sql`
    INSERT INTO test_table (id, name)
    SELECT id, name
    FROM UNNEST(${users.map((user) => user.id)}, ${users.map((user) => user.name)}) as input(id, name);
`;
-- this fails: "Could not choose a best candidate function. You might need to add explicit type casts."
```
I had a look at the code used to validate queries, and since it currently adds type casts to query parameters I think this would be feasible by simply reusing that
